### ISSUE TITLE
error while running

### ISSUE THREAD

**Issue by MaisJamal** [alexiskovi/apollo-tools#1]
I have made a package inside Apollo container, including your python script and a build file like following:

package(default_visibility = ["//visibility:public"])

py_binary(
    name = "launch",
    srcs = ["launch.py"],
    deps = ["//modules/routing/proto:routing_pb2",
            "//cyber/python/cyber_py3:cyber",
            "//cyber/python/cyber_py3:cyber_time",
    ],
)
but when I run the script using: bazel run //launch:launch
I'm getting the following error and it's not launching any module, can you please help me to solve this issue?
[cyber_launch_68689] ERROR Subprocess Popen exception: [Errno 2] No such file or directory: 'mainboard': 'mainboard'
[cyber_launch_68689] ERROR Start manager [localization] failed. Stop all!

**Comment by alexiskovi** [comment]
@MaisJamal, did you build apollo first?

**Comment by MaisJamal** [comment]
yes, I have built apollo with ./apollo.sh build_gpu 
and I'm facing a strange issue after each time I run the script that I can't launch DreamView and I need to do build_gpu one more time.

**Comment by alexiskovi** [comment]
Could you please provide more information about your new package? Did you try to launch any other module after building? Does it works?

**Comment by MaisJamal** [comment]
[launch.zip](https://github.com/alexiskovi/apollo-tools/files/5238144/launch.zip)

I have attached the package, it's located in folder apollo.

after running $ bazel build //launch:launch  , I try to launch the module control for example from terminal and I'm getting the following error:

[cyber_launch_7858] ERROR Subprocess Popen exception: [Errno 2] No such file or directory: 'mainboard': 'mainboard'
[cyber_launch_7858] ERROR Start manager [control] failed. Stop all!
Traceback (most recent call last):
  File "/apollo/cyber/tools/cyber_launch/cyber_launch", line 528, in <module>
    main()
  File "/apollo/cyber/tools/cyber_launch/cyber_launch", line 514, in main
    start(params.file)
  File "/apollo/cyber/tools/cyber_launch/cyber_launch", line 444, in start
    all_died = pmon.run()
  File "/apollo/cyber/tools/cyber_launch/cyber_launch", line 285, in run
    p.get_exit_state()
  File "/apollo/cyber/tools/cyber_launch/cyber_launch", line 200, in get_exit_state
    if self.popen.returncode is None:
AttributeError: 'NoneType' object has no attribute 'returncode'
[cyber_launch_7858] INFO All processes have been stopped.


Have I done something mistakenly?

**Comment by alexiskovi** [comment]
By the way, what is the output of the following line:
`mainboard -d /apollo/modules/control/dag/control.dag` ?
Because it looks like your system can't find `mainboard`, which is responsible for launching modules.
